src/csgo_club_web_app/Controllers/FriendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using csgo_club_web_app.Models;
using CsgoClubEF.Entities;
using CsgoClubEF.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace csgo_club_web_app.Controllers
{
    public class FriendsController : Controller
    {
        private readonly IUnityOfWork _unityOfWork;

        public FriendsController(IUnityOfWork unityOfWork)
        {
            _unityOfWork = unityOfWork;
        }

        public IActionResult Index()
        {
            var id = UInt64.Parse(User.Claims.First().Value.Split("id/")[2]);
            var user = _unityOfWork.GetRepository<User>().Query(x => x.SteamId == id)
                .Include(x=> x.Friends).ThenInclude(x=> x.Friend).FirstOrDefault();
            return View(user);
        }

        public IActionResult Users([FromQuery] string name)
        {
            var users = _unityOfWork.GetRepository<User>().Query(x => x.Name.Contains(name)).ToList();
            return View(users);
        }

        public IActionResult Add([FromRoute] Guid id)
        {
            var steamId = UInt64.Parse(User.Claims.First().Value.Split("id/")[2]);
            var user = _unityOfWork.GetRepository<User>().Query(x => x.SteamId == steamId)
                .Include(x=> x.Friends).ThenInclude(x=> x.Friend).FirstOrDefault();
            if(user.Friends.ToList().Find(x=> x.FriendId == id) != null)
                return Redirect(Url.Action("Index"));
            _unityOfWork.GetRepository<FriendList>().Add(new FriendList()
                {
                    UserId = user.Id,
                    FriendId = id
                });
            _unityOfWork.Save();
            return Redirect(Url.Action("Users"));
        }

        public IActionResult Search() 
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Search(SearchModel model)
        {
            if (ModelState.IsValid)
            {
                return Redirect(Url.Action("Users", new { name = model.Name }));
            }
            return Redirect(Url.Action("Search"));
        }
    }
}

src/csgo_club_web_app/Views/Friends/Index.cshtml
@model CsgoClubEF.Entities.User
@{
    ViewData["Title"] = "Friends List";
}
    <link href="~/css/card.css" rel="stylesheet" type="text/css" />
    <div class="container">
        <div class="main-body">
            <button class="btn btn-primary btn-md p-2 mb-4" type="button" onclick="location.href='@Url.Action("Search", "Friends")'">
                Search User
            </button>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4 gutters-sm">
                @foreach (var f in Model.Friends)
                {
                    var random = new Random();
                    var color = String.Format("#{0:X6}", random.Next(0x1000000));
                    <div class="col mb-3">
                        <div class="card">
                            <div style="background-color:@color; width:100%; height:100px" alt="Cover" class="card-img-top"></div>
                            <div class="card-body text-center">
                                <img src="@f.Friend.ProfilePicture" style="width:100px;height:100px;margin-top:-65px" alt="User" class="img-fluid img-thumbnail rounded-circle border-0 mb-3">
                                <a href="/Profile/Index/@f.Friend.SteamId">
                                    <h5 class="card-title">@f.Friend.Name</h5>
                                </a>
                                <p class="text-muted font-size-sm">@f.Friend.KDR</p>
                                <p class="text-secondary mb-1">@f.Friend.Rank</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

src/csgo_club_web_app/Views/Friends/Search.cshtml
@model csgo_club_web_app.Models.SearchModel
@{
    ViewData["Title"] = "Friends List";
}
<link href="~/css/card.css" rel="stylesheet" type="text/css" />
<div class="container">
    <div class="main-body">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4 gutters-sm">
            <form asp-action="Search" enctype="multipart/form-data" method="post">
                <div class="container">
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" placeholder="Name" />
                    </div>
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

src/csgo_club_web_app/Views/Friends/Users.cshtml
@model List<CsgoClubEF.Entities.User>
@{
    ViewData["Title"] = "Friends List";
}
<link href="~/css/card.css" rel="stylesheet" type="text/css" />
<div class="container">
    <div class="main-body">
        <button class="btn btn-primary btn-md p-2 mb-4" type="button" onclick="location.href='@Url.Action("Search", "Friends")'">
            Search User
        </button>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4 gutters-sm">
            @foreach (var u in Model)
            {
                var random = new Random();
                var color = String.Format("#{0:X6}", random.Next(0x1000000));
                <div class="col mb-3">
                    <div class="card">
                        <div style="background-color:@color; width:100%; height:100px" alt="Cover" class="card-img-top"></div>
                        <div class="card-body text-center">
                            <img src="@u.ProfilePicture" style="width:100px;height:100px;margin-top:-65px" alt="User" class="img-fluid img-thumbnail rounded-circle border-0 mb-3">
                            <a href="/Profile/Index/@u.SteamId">
                                <h5 class="card-title">@u.Name</h5>
                            </a>
                            <p class="text-muted font-size-sm">@u.KDR</p>
                            <p class="text-secondary mb-1">@u.Rank</p>
                        </div>
                        <div class="card-footer">
                            <button onclick="location.href='@Url.Action("Add", "Friends", new { id= u.Id})'" class="btn btn-light btn-sm bg-white has-icon btn-block" type="button"><i class="material-icons"></i>Adicionar</button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>